### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: mailtolink.me | mailto link generator
email: michael@mckvr.com
description: mailto link code and markup generator with subject, body, cc and bcc. Quickly and easily generate code for those annoying mailto links.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mailtolink.me" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#9eebcf'
twitter_username: mmckvr
github_username:  mckeever02
author: Michael Mckeever
logo: card-image.png
twitter:
  card: summary_large_image
  username: mmckvr
social:
  name: Michael Mckeever
  links:
    - https://twitter.com/mmckvr
    - https://github.com/mckeever02

languages: ["en"]
ampdir: amp

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
google_analytics: UA-39366656-21
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
